isolation:
	gcc -Wall -Werror -std=c11 -g isolation.c -o isolation -lm

mm:
	gcc -Wall -Werror -std=c11 -g mm.c -o mm -lm

racer:
	gcc -Wall -Werror -std=c11 -g racer.c -o racer -lm

cheese:
	gcc -Wall -Werror -std=c11 -g cheesefactory.c -o cheesefactory -lm
